### ISSUE TITLE
Display of special character for 'Glyndŵr University'

### ISSUE THREAD

**Issue by iamcreative** [k-int/KBPlus#254]
Just noticed that 'Glyndŵr University' is displaying as 'GlyndÅµr University' in the 'Request New Membership' dropdown of institutional names. Am guessing it's a character encoding issue that needs fixing but in the short term is it worth changing their institutional to 'Glyndwr University' to draw less attention to the problem?

**Comment by ostephens** [comment]
Encoding issue on data import file "subscribing organisations.csv". Have saved as utf8 and renamed "subscribing organisations.csv_utf8". This should correct on next import

**Comment by ostephens** [comment]
Still seems to be a problem on this - @ianibo can you see what the issue is?  Checking on Live where you've done the most recent data load and with the utf8 version of the file

**Comment by ianibo** [comment]
Fixed on live.

**Comment by iamcreative** [comment]
This is still broken for me - now it says 'Glend?r University'

**Comment by ostephens** [comment]
Hmm - broken for me again now. Was fixed previously. No change to the data file as far as I can see - @ianibo can you have a look on Sunday?

**Comment by iamcreative** [comment]
Now fixed in both Live and Sandpit

**Comment by ianibo** [comment]
Not sure what all the bouncing around was.. Nothing changed on the live dataload. Please reopen if it comes back - although if it does we're in serious bother having done the dataload.
